Traceback (most recent call last):
  File "/home/osboxes/git/SmallProjects/Tutorials/debugging.py", line 17, in <module>
    raise Exception ('This is an error message.')
Exception: This is an error message.
