Traceback (most recent call last):
  File "/home/osboxes/git/SmallProjects/debugging/Tutorials/debugging.py", line 15, in <module>
    raise Exception ('This is an error message.')
Exception: This is an error message.
